### ISSUE TITLE
multiple symlinks for same origin not working

### ISSUE THREAD

**Issue by mr-jingles** [bragento/bragento-composer-installer#22]
Recently I had a problem installing:

https://github.com/madalinoprea/magneto-debug.git

It has a modman file were some folders and files are linked to frontend and adminhtml area. The adminhtml part gets linked whereas the frontend part doesn't. I had to double the original files in order two link both:

https://github.com/mr-jingles/magneto-debug.git

Here is the comparison of the two modman files:

https://github.com/madalinoprea/magneto-debug/blob/master/modman

and

https://github.com/mr-jingles/magneto-debug/blob/master/modman

**Comment by davidverholen** [comment]
Hey @mr-jingles,

I think I know what the Problem is. I'm bulding an associated array with the source as key for the mappings. So when a source is present multiple times, it gets overwritten.

I'll fix this as soon as a have the time. Currently, I'm also developing a complete new Version of the Installer under my own namespace. More to come if it gets near completion.

**Comment by davidverholen** [comment]
Hey @mr-jingles ,

the package seems to work now with the new beta 1.1.2 of the installer. (only the dev Version since the only release v-1.0.0 is not a valid composer  version string)

**Comment by mr-jingles** [comment]
Thx - I will test it now! :)

**Comment by mr-jingles** [comment]
Unfortunately using 1.1.2-beta1 gives me an error: 

PHP Fatal error:  Class 'Bragento\Magento\Composer\Installer\Util\String' not found in /*/*/*/vendor/bragento/magento-composer-installer/src/Util/Filesystem.php on line 226

**Comment by davidverholen** [comment]
this error only occurs during the update of the installer because composer still has the old class loaded which requires the class String.

This class has been renamed to StringUtil since String is not allowed anymore in php7

To avoid this error during composer Plugin updates you have to use the --no-plugins switch with composer update.

**Comment by mr-jingles** [comment]
Thanks for clarifying this!
